name: Build and Push Docker Image

env:
  DOCKER_IMAGE_NAME: erickmontesdk/docker_githubactions_aws-ec2
  DOCKER_REGISTRY: ghcr.io
  DOCKER_USERNAME: ${{ github.actor }}
  DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

  EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
  EC2_HOST: ${{ secrets.EC2_HOST }}
  EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}

  # AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  # LAMBDA_FUNCTION_NAME: ${{ secrets.LAMBDA_FUNCTION_NAME }}
  LAMBDA_URL: ${{ secrets.LAMBDA_URL }}

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-push-landing-page:
    name: Build and Push Landing Page Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:latest
          cache-from: type=registry,ref=${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:buildcache,mode=max

      - name: Deploy to EC2
        id: deploy  
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ env.EC2_USERNAME }}
          key: ${{ env.EC2_SSH_KEY }}
          script: |
            echo ${{ env.DOCKER_PASSWORD }} | sudo docker login ghcr.io -u ${{ env.DOCKER_USERNAME }} --password-stdin
            sudo docker pull ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:latest
            sudo docker stop actions_nextjs || true
            sudo docker rm actions_nextjs || true
            sudo docker run -d --name actions_nextjs -p 80:3000 ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:latest


      - name: Invoke Lambda
        if: always()  
        run: |
          STATUS="${{ job.status }}"
          if [ "$STATUS" = "success" ]; then
            MESSAGE="Deploy in EC2 succeeded. Repo: ${{ github.repository }}, Commit: ${{ github.sha }}, Run ID: ${{ github.run_id }}"
          else
            MESSAGE="Deploy in EC2 failed. Repo: ${{ github.repository }}, Commit: ${{ github.sha }}, Run ID: ${{ github.run_id }}. Error in step: ${{ steps.deploy.outcome || 'unknown' }}"
          fi
          

          #Gather metadata
          COMMIT_SHA="${{ github.sha }}"
          BRANCH="${{ github.ref.name }}"
          ACTOR="${{ github.actor }}"
          TIMESTAMP=$(date)

          RESPONSE=$(curl -s -X POST ${{env.LAMBDA_URL}} \
            -H "Content-Type: application/json" \
            -d "{\"status\": \"$STATUS\", 
            \"message\": \"$MESSAGE\", 
            \"repo\": \"${{ github.repository }}\", 
            \"commit\": \"$COMMIT_SHA \"}"
            \"triggered_by\": \"$ACTOR\"}"
            \"timestamp\": \"$TIMESTAMP\"}")

      
          echo "Response from Lambda:"
          echo "$RESPONSE"